default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: kiprosh
development:
  <<: *default
  database: multitenant_development

test:
  <<: *default
  database: multitenant_test

production:
  <<: *default
  database: multitenant_production
